using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Threading;
using System.Windows.Forms;

namespace SpeedExplorer;

public partial class ImageViewerForm : Form
{
    private readonly List<string> _imagePaths;
    private int _currentIndex;
    private Image? _currentImage;
    private AnimatedImageSequence? _currentAnimation;
    private readonly System.Windows.Forms.Timer _animationTimer;
    private int _animationFrameIndex;
    
    private PictureBox _pictureBox = null!;
    private ContextMenuStrip _imageContextMenu = null!;
    private Panel _contentPanel = null!;
    private Panel _controlPanel = null!;
    private Panel _titleBar = null!;
    private Label _titleLabel = null!;
    
    private Panel _infoContainer = null!;
    private Label _fileNameLabel = null!;
    private Label _indexLabel = null!;
    private FlowLayoutPanel _tagsPanel = null!;
    private TrackBar _zoomSlider = null!;
    private Label _zoomLabel = null!;
    private Panel _aiPanel = null!;
    private RichTextBox _aiOutputBox = null!;
    private Label _aiStatusLabel = null!;
    private TextBox _targetLanguageBox = null!;
    private TextBox _sourceLanguageHintBox = null!;
    private TextBox _ocrHintBox = null!;
    private TextBox _translationContextHintBox = null!;
    private CheckBox _manualMaxEffortCheck = null!;
    private CheckBox _ocrReasoningCheck = null!;
    private CheckBox _translationReasoningCheck = null!;
    private CheckBox _overlayToggle = null!;
    private CheckBox _showSavedOcrCheck = null!;
    private CheckBox _showSavedTranslationCheck = null!;
    private Button _prevBtn = null!;
    private Button _nextBtn = null!;
    private Button _zoomOutBtn = null!;
    private Button _zoomInBtn = null!;
    private Button _fitBtn = null!;
    private Button _actualBtn = null!;
    private Button _rotateBtn = null!;
    private Button _fullscreenBtn = null!;
    private Button _aiToggleBtn = null!;
    private Button _ocrBtn = null!;
    private Button _translateBtn = null!;
    private Button _drawOcrBoxBtn = null!;
    private Button _clearManualOcrBoxesBtn = null!;
    private Button _tagBtn = null!;
    private Button _clearOverlayBtn = null!;
    private Button _deleteSavedTranslationBtn = null!;
    private Button _copyResultBtn = null!;
    private Button _abortBtn = null!;
    private Button _cancelCurrentJobBtn = null!;
    private Button _openSavedOcrFileBtn = null!;
    private Button _closeBtn = null!;
    private ToolStripMenuItem _editOverlayBlockMenuItem = null!;
    private readonly LlmService _llmService = new();
    private CancellationTokenSource? _aiCts;
    private CancellationTokenSource? _tagCts;
    private string? _activeTagImagePath;
    private FileSystemWatcher? _imageFolderWatcher;
    private readonly System.Windows.Forms.Timer _imageFolderRefreshTimer;
    private string? _watchedImageFolder;

    private float _zoomLevel = 1.0f;
    private Point _panOffset = Point.Empty;
    private Point _lastMousePos;
    private bool _isPanning;
    private DateTime _lastPictureBoxLeftMouseUpUtc = DateTime.MinValue;
    private DateTime _pictureBoxSecondClickDownUtc = DateTime.MinValue;
    private Point _lastPictureBoxLeftMouseUpPoint;
    private readonly AppSettings _settings = AppSettings.Current;
    private bool _isFullscreen;
    private FormWindowState _previousWindowState;
    private bool _autoFitEnabled = true;
    private bool _autoFitBySmallerDimension;
    private int _rotationQuarterTurns;
    private bool _suppressZoomSliderEvent;
    private bool _aiBusy;
    private string? _ocrImagePath;
    private LlmImageTextResult? _lastOcrResult;
    private LlmTextTranslationResult? _savedTranslationForCurrentImage;
    private List<string> _lastTranslations = new();
    private readonly List<OverlayTextBlock> _overlayBlocks = new();
    private OverlayStyleDefaults? _currentImageOverlayDefaults;
    private bool _currentOverlayFromSavedCache;
    private bool _suppressSavedTranslationToggleEvent;
    private bool _showSavedTranslationPreferred;
    private bool _manualOcrDrawMode;
    private bool _isDrawingManualOcrRegion;
    private bool _cornerCloseHover;
    private int _contextOverlayBlockIndex = -1;
    private OverlayDragMode _overlayDragMode = OverlayDragMode.None;
    private int _overlayDragBlockIndex = -1;
    private string? _overlayDragImagePath;
    private Point _overlayDragStartPoint;
    private RectangleF _overlayDragStartRect;
    private bool _overlayDragStartHadUserOverride;
    private bool _overlayDragChanged;
    private Point _manualOcrDragStart;
    private Point _manualOcrDragCurrent;
    private readonly List<ManualOcrRegion> _pendingManualOcrRegions = new();
    private readonly List<ImageAiJob> _queuedAiJobs = new();
    private readonly Dictionary<string, int> _queuedAiJobCountsByImage = new(StringComparer.OrdinalIgnoreCase);
    private readonly Dictionary<string, List<RectangleF>> _queuedManualRegionsByImage = new(StringComparer.OrdinalIgnoreCase);
    private readonly Dictionary<string, List<RectangleF>> _restorableManualRegionsByImage = new(StringComparer.OrdinalIgnoreCase);
    private ImageAiJob? _activeAiJob;
    private bool _cancelActiveAiJobOnly;

    private const string OcrCacheJsonSeparator = "###__OCR_CACHE_JSON__###";
    
    private static readonly Color BackColor_Dark = Color.FromArgb(20, 20, 20);
    private static readonly Color ControlPanelColor = Color.FromArgb(40, 40, 40);
    private static readonly Color ForeColor_Dark = Color.FromArgb(240, 240, 240);
    private static readonly Color TitleBarColor = Color.FromArgb(32, 32, 32);
    private static readonly Color DefaultOverlayFillColor = Color.FromArgb(242, 7, 19, 36);
    private static readonly Color DefaultOverlayBorderColor = Color.FromArgb(220, 125, 198, 255);
    private static readonly Color DefaultOverlayTextColor = Color.FromArgb(250, 250, 250);
    private static readonly Color DefaultOverlayTextOutlineColor = Color.FromArgb(255, 0, 0, 0);

    private int Scale(int pixels) => (int)(pixels * (this.DeviceDpi / 96.0));
    private Padding Scale(Padding p) => new Padding(Scale(p.Left), Scale(p.Top), Scale(p.Right), Scale(p.Bottom));
    private int TitleBarHeight => Scale(32);
    private int ControlPanelHeight => Scale(50);
    private int ControlButtonHeight => Scale(24);
    private int ZoomSliderVisualOffsetY => Scale(2);
    private Padding WindowFramePadding => Scale(new Padding(2));

    private readonly ImageViewerSortOptions? _sortOptions;

}
